### ISSUE TITLE
Would be good to let people know this is Linux only

### ISSUE THREAD

**Issue by feoh** [kiwanami/emacs-skype#6]
And won't work on Windows or the Mac.

**Comment by kiwanami** [comment]
Thank you for your advice.
I added a readme file and wrote it.

**Comment by sevos** [comment]
So it won't work on OS X, even if I compiled emacs with dbus & installed 32bit python? I managed to run the proxy script and it makes the computer to beep and prints OK. I installed dbus from homebrew, but still getting "No connection to bus" error in emacs, when I try to invoke "skype--open-all-users-buffer-command". Any ideas how to debug this?
